Page({
    data:{
        left:'',
        top:''
    },
    viewTouchMove:function(e){
        this.setData({
            left:e.touches[0].clientX-60,
            top:e.touches[0].clientY-60
        })
    }
})