# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fristapp', '0002_aritcle'),
    ]

    operations = [
        migrations.AddField(
            model_name='aritcle',
            name='tag',
            field=models.CharField(blank=True, choices=[('tech', 'Tech'), ('life', 'Life')], max_length=5, null=True),
        ),
    ]
